import { createFileRoute } from "@tanstack/react-router";
import { SiteShell } from "@/components/site/SiteShell";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "About — Prophiq" },
      { name: "description", content: "How Prophiq's multi-model consensus works." },
    ],
  }),
  component: AboutPage,
});

function AboutPage() {
  return (
    <SiteShell>
      <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24">
        <h1 className="text-3xl font-bold tracking-tight text-[var(--brand-ink)] sm:text-4xl">
          About Prophiq
        </h1>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-slate-700 sm:text-base">
          <section>
            <h2 className="text-lg font-semibold text-[var(--brand-ink)]">What Prophiq is</h2>
            <p className="mt-2">
              Prophiq is a consensus forecasting engine. For every upcoming public event — a football
              final, an election, a central-bank decision, an awards ceremony — we run three
              independent frontier AI models in parallel, fuse their rankings into a single
              consensus prediction, and publish the result with full reasoning. You can browse the
              feed, ask follow-up questions in a chat panel on any event, or submit your own question
              and watch the pipeline run live.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--brand-ink)]">How it works</h2>
            <ol className="mt-3 list-decimal space-y-3 pl-5">
              <li>
                <strong className="text-[var(--brand-ink)]">Discovery.</strong> An autonomous cron
                scans public sources every few hours for new events across sport, politics, markets,
                and entertainment. Each event is validated, classified into a domain, and stored with
                structured metadata.
              </li>
              <li>
                <strong className="text-[var(--brand-ink)]">Multi-model fan-out.</strong> For every
                event, three frontier language models research the context independently and rank the
                possible outcomes by likelihood. Each model works from the same evidence but reasons
                in its own way.
              </li>
              <li>
                <strong className="text-[var(--brand-ink)]">Borda consensus.</strong> The
                individual rankings are merged with a weighted Borda count. The algorithm rewards
                outcomes that multiple models rank highly, while surfacing "dark horses" — outcomes
                one model championed but others overlooked.
              </li>
              <li>
                <strong className="text-[var(--brand-ink)]">Scoring.</strong> After the event
                resolves, the actual outcome is compared against the prediction. We record top-pick
                accuracy, top-3 hit rate, and an overall grade so the track record stays honest.
              </li>
            </ol>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--brand-ink)]">Why three models</h2>
            <p className="mt-2">
              A single model can be confidently wrong. Three independent models, drawn from
              different providers and architectures, give us diversity of reasoning, robustness
              against any one model's blind spots, and a natural calibration signal: when all three
              agree, the prediction is usually well-founded; when they diverge, the disagreement
              itself is information.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--brand-ink)]">What it's not</h2>
            <p className="mt-2">
              Prophiq is not a betting tipster, not a financial adviser, and not a crystal ball. The
              predictions are probabilistic forecasts generated by language models, not guarantees.
              Markets coverage is informational only. Politics coverage is non-partisan. Sport odds
              framing is for entertainment — please{" "}
              <a
                href="https://www.begambleaware.org"
                target="_blank"
                rel="noopener noreferrer"
                className="underline hover:text-[var(--brand-ink)]"
              >
                gamble responsibly
              </a>
              .
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--brand-ink)]">Acknowledgements</h2>
            <p className="mt-2">
              Prophiq's consensus engine calls models from Anthropic, OpenAI, and Google. Research
              and context gathering are powered by Perplexity. Data storage, auth, edge functions, and
              real-time subscriptions run on Supabase.
            </p>
          </section>
        </div>
      </div>
    </SiteShell>
  );
}
