/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SportRouteImport } from './routes/sport'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as PoliticsRouteImport } from './routes/politics'
import { Route as MyQuestionsRouteImport } from './routes/my-questions'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HealthcheckRouteImport } from './routes/healthcheck'
import { Route as EntertainmentRouteImport } from './routes/entertainment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AskedRouteImport } from './routes/asked'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminMarqueeRouteImport } from './routes/admin.marquee'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminCostsRouteImport } from './routes/admin.costs'
import { Route as AdminCalibrationRouteImport } from './routes/admin.calibration'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as DomainTrackRecordRouteImport } from './routes/$domain.track-record'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as ApiOgHomeRouteImport } from './routes/api/og/home'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as DomainEventsSlugRouteImport } from './routes/$domain.events.$slug'
import { Route as ApiOgEventSlugRouteImport } from './routes/api/og/event/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SportRoute = SportRouteImport.update({
  id: '/sport',
  path: '/sport',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticsRoute = PoliticsRouteImport.update({
  id: '/politics',
  path: '/politics',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQuestionsRoute = MyQuestionsRouteImport.update({
  id: '/my-questions',
  path: '/my-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcheckRoute = HealthcheckRouteImport.update({
  id: '/healthcheck',
  path: '/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const EntertainmentRoute = EntertainmentRouteImport.update({
  id: '/entertainment',
  path: '/entertainment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AskedRoute = AskedRouteImport.update({
  id: '/asked',
  path: '/asked',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarqueeRoute = AdminMarqueeRouteImport.update({
  id: '/marquee',
  path: '/marquee',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCostsRoute = AdminCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalibrationRoute = AdminCalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const DomainTrackRecordRoute = DomainTrackRecordRouteImport.update({
  id: '/$domain/track-record',
  path: '/$domain/track-record',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiOgHomeRoute = ApiOgHomeRouteImport.update({
  id: '/api/og/home',
  path: '/api/og/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRoute,
} as any)
const DomainEventsSlugRoute = DomainEventsSlugRouteImport.update({
  id: '/$domain/events/$slug',
  path: '/$domain/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgEventSlugRoute = ApiOgEventSlugRouteImport.update({
  id: '/api/og/event/$slug',
  path: '/api/og/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/asked': typeof AskedRoute
  '/contact': typeof ContactRoute
  '/entertainment': typeof EntertainmentRoute
  '/healthcheck': typeof HealthcheckRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/my-questions': typeof MyQuestionsRoute
  '/politics': typeof PoliticsRoute
  '/predictions': typeof PredictionsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/receipts': typeof ReceiptsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sport': typeof SportRoute
  '/terms': typeof TermsRoute
  '/$domain/track-record': typeof DomainTrackRecordRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/calibration': typeof AdminCalibrationRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/marquee': typeof AdminMarqueeRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/': typeof AdminIndexRoute
  '/$domain/events/$slug': typeof DomainEventsSlugRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/og/home': typeof ApiOgHomeRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/og/event/$slug': typeof ApiOgEventSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ask': typeof AskRoute
  '/asked': typeof AskedRoute
  '/contact': typeof ContactRoute
  '/entertainment': typeof EntertainmentRoute
  '/healthcheck': typeof HealthcheckRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/my-questions': typeof MyQuestionsRoute
  '/politics': typeof PoliticsRoute
  '/predictions': typeof PredictionsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/receipts': typeof ReceiptsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sport': typeof SportRoute
  '/terms': typeof TermsRoute
  '/$domain/track-record': typeof DomainTrackRecordRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/calibration': typeof AdminCalibrationRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/marquee': typeof AdminMarqueeRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin': typeof AdminIndexRoute
  '/$domain/events/$slug': typeof DomainEventsSlugRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/og/home': typeof ApiOgHomeRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/api/og/event/$slug': typeof ApiOgEventSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/asked': typeof AskedRoute
  '/contact': typeof ContactRoute
  '/entertainment': typeof EntertainmentRoute
  '/healthcheck': typeof HealthcheckRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/my-questions': typeof MyQuestionsRoute
  '/politics': typeof PoliticsRoute
  '/predictions': typeof PredictionsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/receipts': typeof ReceiptsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sport': typeof SportRoute
  '/terms': typeof TermsRoute
  '/$domain/track-record': typeof DomainTrackRecordRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/calibration': typeof AdminCalibrationRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/marquee': typeof AdminMarqueeRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/': typeof AdminIndexRoute
  '/$domain/events/$slug': typeof DomainEventsSlugRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/og/home': typeof ApiOgHomeRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/og/event/$slug': typeof ApiOgEventSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/ask'
    | '/asked'
    | '/contact'
    | '/entertainment'
    | '/healthcheck'
    | '/how-it-works'
    | '/markets'
    | '/my-questions'
    | '/politics'
    | '/predictions'
    | '/pricing'
    | '/privacy'
    | '/receipts'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/sport'
    | '/terms'
    | '/$domain/track-record'
    | '/admin/audit'
    | '/admin/calibration'
    | '/admin/costs'
    | '/admin/health'
    | '/admin/marquee'
    | '/admin/revenue'
    | '/admin/'
    | '/$domain/events/$slug'
    | '/admin/users/$id'
    | '/api/og/home'
    | '/admin/users/'
    | '/api/og/event/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/ask'
    | '/asked'
    | '/contact'
    | '/entertainment'
    | '/healthcheck'
    | '/how-it-works'
    | '/markets'
    | '/my-questions'
    | '/politics'
    | '/predictions'
    | '/pricing'
    | '/privacy'
    | '/receipts'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/sport'
    | '/terms'
    | '/$domain/track-record'
    | '/admin/audit'
    | '/admin/calibration'
    | '/admin/costs'
    | '/admin/health'
    | '/admin/marquee'
    | '/admin/revenue'
    | '/admin'
    | '/$domain/events/$slug'
    | '/admin/users/$id'
    | '/api/og/home'
    | '/admin/users'
    | '/api/og/event/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/ask'
    | '/asked'
    | '/contact'
    | '/entertainment'
    | '/healthcheck'
    | '/how-it-works'
    | '/markets'
    | '/my-questions'
    | '/politics'
    | '/predictions'
    | '/pricing'
    | '/privacy'
    | '/receipts'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/sport'
    | '/terms'
    | '/$domain/track-record'
    | '/admin/audit'
    | '/admin/calibration'
    | '/admin/costs'
    | '/admin/health'
    | '/admin/marquee'
    | '/admin/revenue'
    | '/admin/'
    | '/$domain/events/$slug'
    | '/admin/users/$id'
    | '/api/og/home'
    | '/admin/users/'
    | '/api/og/event/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AskRoute: typeof AskRoute
  AskedRoute: typeof AskedRoute
  ContactRoute: typeof ContactRoute
  EntertainmentRoute: typeof EntertainmentRoute
  HealthcheckRoute: typeof HealthcheckRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketsRoute: typeof MarketsRoute
  MyQuestionsRoute: typeof MyQuestionsRoute
  PoliticsRoute: typeof PoliticsRoute
  PredictionsRoute: typeof PredictionsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportRoute: typeof SportRoute
  TermsRoute: typeof TermsRoute
  DomainTrackRecordRoute: typeof DomainTrackRecordRoute
  DomainEventsSlugRoute: typeof DomainEventsSlugRoute
  ApiOgHomeRoute: typeof ApiOgHomeRoute
  ApiOgEventSlugRoute: typeof ApiOgEventSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sport': {
      id: '/sport'
      path: '/sport'
      fullPath: '/sport'
      preLoaderRoute: typeof SportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politics': {
      id: '/politics'
      path: '/politics'
      fullPath: '/politics'
      preLoaderRoute: typeof PoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-questions': {
      id: '/my-questions'
      path: '/my-questions'
      fullPath: '/my-questions'
      preLoaderRoute: typeof MyQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcheck': {
      id: '/healthcheck'
      path: '/healthcheck'
      fullPath: '/healthcheck'
      preLoaderRoute: typeof HealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entertainment': {
      id: '/entertainment'
      path: '/entertainment'
      fullPath: '/entertainment'
      preLoaderRoute: typeof EntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asked': {
      id: '/asked'
      path: '/asked'
      fullPath: '/asked'
      preLoaderRoute: typeof AskedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marquee': {
      id: '/admin/marquee'
      path: '/marquee'
      fullPath: '/admin/marquee'
      preLoaderRoute: typeof AdminMarqueeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/costs': {
      id: '/admin/costs'
      path: '/costs'
      fullPath: '/admin/costs'
      preLoaderRoute: typeof AdminCostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calibration': {
      id: '/admin/calibration'
      path: '/calibration'
      fullPath: '/admin/calibration'
      preLoaderRoute: typeof AdminCalibrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$domain/track-record': {
      id: '/$domain/track-record'
      path: '/$domain/track-record'
      fullPath: '/$domain/track-record'
      preLoaderRoute: typeof DomainTrackRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/og/home': {
      id: '/api/og/home'
      path: '/api/og/home'
      fullPath: '/api/og/home'
      preLoaderRoute: typeof ApiOgHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$domain/events/$slug': {
      id: '/$domain/events/$slug'
      path: '/$domain/events/$slug'
      fullPath: '/$domain/events/$slug'
      preLoaderRoute: typeof DomainEventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/event/$slug': {
      id: '/api/og/event/$slug'
      path: '/api/og/event/$slug'
      fullPath: '/api/og/event/$slug'
      preLoaderRoute: typeof ApiOgEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCalibrationRoute: typeof AdminCalibrationRoute
  AdminCostsRoute: typeof AdminCostsRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminMarqueeRoute: typeof AdminMarqueeRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCalibrationRoute: AdminCalibrationRoute,
  AdminCostsRoute: AdminCostsRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminMarqueeRoute: AdminMarqueeRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AskRoute: AskRoute,
  AskedRoute: AskedRoute,
  ContactRoute: ContactRoute,
  EntertainmentRoute: EntertainmentRoute,
  HealthcheckRoute: HealthcheckRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketsRoute: MarketsRoute,
  MyQuestionsRoute: MyQuestionsRoute,
  PoliticsRoute: PoliticsRoute,
  PredictionsRoute: PredictionsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReceiptsRoute: ReceiptsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportRoute: SportRoute,
  TermsRoute: TermsRoute,
  DomainTrackRecordRoute: DomainTrackRecordRoute,
  DomainEventsSlugRoute: DomainEventsSlugRoute,
  ApiOgHomeRoute: ApiOgHomeRoute,
  ApiOgEventSlugRoute: ApiOgEventSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
